# Dockerfile-ui


# Use a specific Node.js version
FROM node:18-alpine

# Set working directory
WORKDIR /ostadui

# Copy package.json and package-lock.json for caching
COPY OstadUI/package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY OstadUI/ .

# Expose the development server port
EXPOSE 5173

# Run the development server
CMD ["npm", "run", "dev"]
